# ansible/playbooks/ops/iscsi-logout.yml
---
- name: Log out from iSCSI target
  hosts: all
  become: true
  tasks:
    - name: Log out from iSCSI target
      community.general.open_iscsi:
        portal: "{{ iscsi_target_ip }}"
        port: "{{ iscsi_target_port }}"
        target: "{{ iscsi_target_iqn }}"
        login: "no"
      when: iscsi_enabled | bool
