---
extends: relaxed

rules:
  line-length:
    max: 160
    level: warning
  empty-lines:
    max: 2
  comments:
    min-spaces-from-content: 1
  octal-values:
    forbid-implicit-octal: false  # Allow implicit octals like 0755 (required for Docker Swarm mode/permissions)
    forbid-explicit-octal: true
